version: '3.9'

networks:
  cicd_net:
    driver: bridge

services:
  front_nginx:
    container_name: reverse_proxy_nginx
    build: ./front/
    restart: always
    privileged: true
    ports:
      - "80:80"
    volumes:
      -