version: '3.8'

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./.ssh:/root/.ssh


